### ISSUE TITLE
[Bug]: Accessibility is not supported by default

### ISSUE THREAD

**Issue by ILikeYourHat** [lynx-family/lynx#641]
### System Info

Not relevant

### Details

Hi, I've noticed that despite having a whole documentation section about [accessibility support](https://lynxjs.org/guide/inclusion/accessibility.html), in reality tools like TalkBack are not working for Lynx screens. I've confirmed it through custom integration with my application, but same is happening for the LynxExplorer application. TalkBack is not able to focus on elements like text areas, buttons etc.

### Reproduce Steps

1. Download the LynxExplorer application from the [release page](https://github.com/lynx-family/lynx/releases/tag/3.2.0-rc.1)
2. Open the app, go to "Showcase"
3. Enable TalkBack
4. Try to use it to navigate on this screen, e.g. entering any section

**Comment by ILikeYourHat** [comment]
Some clarification: this seems to affect only Android. iOS is working as expected

**Comment by toretto-wt** [comment]
@ILikeYourHat Yes, it should only appear on Android. Maybe I know the reason, let me take a look.

**Comment by toretto-wt** [comment]
https://github.com/lynx-family/lynx/pull/670

**Comment by toretto-wt** [comment]
@ILikeYourHat We have fixed the relevant issues in the latest develop branch. You can build an explorer APP locally and testing, or wait for Lynx to release the latest APP.

**Comment by ILikeYourHat** [comment]
Hi, I assume the fix was added in this commit? 
https://github.com/lynx-family/lynx/commit/f8ce48c448d367dbd377659d941819742b7d274a

The problem was misunderstood. LynxExplorer was given as an easy example to show that the accessibility handling is broken on Android. Adding a11y labels makes no difference in this case (verified), I'm still not able to use TalkBack. We have internally prepared a Lynx bundle, following your a11y documentation,  that was used both on Android and iOS. The result is, screen reader was working fine on iOS, but not working at all on Android. I assume there is an issue somewhere in the internal a11y logic in the Android library, that prevents TalkBack from working. Missing labels are not the issue here

**Comment by darekbx** [comment]
@ILikeYourHat I know where's the problem. You just need to open the app with turned on Accessbility, then the app is properly being read by TalkBack. However, this is still some kind of problem when users turn on A11y when app is opened, then TalkBack is not working.

**Comment by ILikeYourHat** [comment]
I've tested it again (on emulator, not physical device) and here it works fine, even if TalkBack is enabled directly on given screen. So I suspect this is some issue with TalkBack itself, or with the OS, but at this point I'm really not sure what had happened

**Comment by ILikeYourHat** [comment]
Ok, now I know what's actually happening.

The issue is that Lynx has the possibility to flatten elements with text inside, drawing it directly on the LynxView. Such elements are obviously not recognized by TalkBack, so the accessibility doesn't work for them. This might be seen as a bug or a feature, depending of what you want to achieve. But I've noticed a clever workaround: when Lynx detects TalkBack during the initialization phase, it prevents text areas from being flattened. So, if you have TalkBack already enabled, then you have application that is responsive. BUT if you enable TalkBack on that screen, the Lynx content stays the same (so it is optimized), so application is not responsive.

What's interesting, setting "accessibility-element={true}" prop has no impact of the above logic. If TalkBack is disabled, then even elements with "accessibility-element={true} would be flattened and ignored by TalkBack.

I don't know how to handle this situation, because it was clearly a design decision related to view optimisations. What I would suggest is:
- improve the a11y documentation, to clearly point out the above issue
- add a parameter to the engine (something like "A11Y_ENABLED_ALWAYS" and "A11Y_ENABLED_IF_NEEDED") to clearly indicate how the Lynx would behave in such situations, or
- add some kind of callback when TalkBack (or other a11y service) is detected, and then re-render the current visible Lynx View

Sorry for the confusion I've caused in this topic, I've not checked the underlying issue close enough
